services:
  nginx:
    container_name: nginx
    restart: always
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    ports:
      - "8080:80"

  postgres:
    container_name: postgres_db
    image: postgres
    restart: always
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres

volumes:
  postgres_volume:
